### ISSUE TITLE
加载bib文件发生 KeyError问题

### ISSUE THREAD

**Issue by whkwss** [sheldonxxd/obsidian_vault_template_for_researcher#24]
## ISSUE TEMPLATE

In order to solve the problem more efficiently, please submit the issue according to this template. 

### Environment

1. **Vault template release version**: v1.5
2. **Operating system**: windows
3. **Python version**: 3.8
4. **Zotero version**: 6.0
5. **Pandoc version**No
6. **Obsidian version**: 0.14.5

### Bug descryption

使用`引文列表`功能时，加载MyLibrary.bib出现问题
我已为该问题寻找到一个解决方案，但不知道是不是我一开始的Better bibetex设置有问题。
参考https://github.com/sciunto-org/python-bibtexparser/issues/222

修改前`load()`函数：
```python
    def load(self, fp, test=False):
        '''
        load the library.bib
        '''
        with open(fp, encoding='utf-8') as bibtex_file:
            bib_database = bibtexparser.load(bibtex_file)
        self.library = bib_database.entries_dict
        if test:
            print('{} entries loaded!'.format(len(self.library)))
```
修改后load()函数
```python
    def load(self, fp, test=False):
        '''
        load the library.bib
        '''
        parser = BibTexParser(common_strings=True)
        with open(fp, encoding='utf-8') as bibtex_file:
            bib_database = bibtexparser.load(bibtex_file,parser)
        self.library = bib_database.entries_dict
        if test:
            print('{} entries loaded!'.format(len(self.library)))
```

### Obsidian console information
报错内容：
```python
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bibdatabase.py", line 107, in expand_string
    self.strings[name])
KeyError: 'sep'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./08-Assets/Scripts/ref_list.py", line 73, in <module>
    main()
  File "./08-Assets/Scripts/ref_list.py", line 12, in main
    hwj.load(vault.paths['bib'])
  File "C:\Users\lenovo\Desktop\CURRENTWORK\5.note\1.work_station\08-Assets\Scripts\obs.py", line 59, in load
    bib_database = bibtexparser.load(bibtex_file)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\__init__.py", line 69, in load
    return parser.parse_file(bibtex_file)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bparser.py", line 169, in parse_file
    return self.parse(file.read(), partial=partial)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bparser.py", line 147, in parse
    self._expr.parseFile(bibtex_file_obj)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bibtexexpression.py", line 278, in parseFile
    return self.main_expression.parseFile(file_obj, parseAll=True)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 2563, in parseFile
    return self.parseString(file_contents, parseAll)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 1937, in parseString
    loc, tokens = self._parse(instring, 0)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 4764, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 4690, in parseImpl
    loc, tmptokens = self_expr_parse(instring, preloc, doActions)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 4237, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 1710, in _parseNoCache
    tokens = fn(instring, tokensStart, retTokens)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\pyparsing.py", line 1316, in wrapper
    ret = func(*args[limit[0]:])
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bparser.py", line 187, in <lambda>
    lambda s, l, t: self._add_entry(
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bparser.py", line 277, in _add_entry
    d[self._clean_field_key(key)] = self._clean_val(fields[key])
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bparser.py", line 228, in _clean_val
    return as_text(val)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bibdatabase.py", line 270, in as_text
    return text_string_or_expression.get_value()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bibdatabase.py", line 231, in get_value
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bibdatabase.py", line 231, in <listcomp>
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bibdatabase.py", line 197, in expand_string
    return string_or_bibdatastring.get_value()
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bibdatabase.py", line 178, in get_value
    return self._bibdatabase.expand_string(self.name)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python38\lib\site-packages\bibtexparser\bibdatabase.py", line 109, in expand_string
    raise(UndefinedString(name))
bibtexparser.bibdatabase.UndefinedString: 'sep'
```

**Comment by sheldonxxd** [comment]
> KeyError: 'sep'

看上去是 reference 中关于月份的字符串解析引起的错误，如果这个字段不是很重要的话，可以在 better bibtex 插件中 omit 掉：

![image](https://user-images.githubusercontent.com/42539486/169630004-3468175a-6606-49d4-b1cd-238db420af8e.png)

**Comment by whkwss** [comment]
> > KeyError: 'sep'
> 
> 看上去是 reference 中关于月份的字符串解析引起的错误，如果这个字段不是很重要的话，可以在 better bibtex 插件中 omit 掉：
> 
> ![image](https://user-images.githubusercontent.com/42539486/169630004-3468175a-6606-49d4-b1cd-238db420af8e.png)

感谢！

> > KeyError: 'sep'
> 
> 看上去是 reference 中关于月份的字符串解析引起的错误，如果这个字段不是很重要的话，可以在 better bibtex 插件中 omit 掉：
> 
> ![image](https://user-images.githubusercontent.com/42539486/169630004-3468175a-6606-49d4-b1cd-238db420af8e.png)

可以解决，感谢！
