### ISSUE TITLE
author rannking统计按钮无法使用

### ISSUE THREAD

**Issue by j89180192** [sheldonxxd/obsidian_vault_template_for_researcher#32]
使用test测试后反馈如下，本人计算机小白，现在很是着急55

### Bug descryption

Traceback (most recent call last):
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bibdatabase.py", line 107, in expand_string
    self.strings[name])
KeyError: 'apr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./08-Assets/Scripts/author_count.py", line 58, in <module>
    main()
  File "./08-Assets/Scripts/author_count.py", line 16, in main
    xxd.load(bib)
  File "D:\����\working\08-Assets\Scripts\obs.py", line 59, in load
    bib_database = bibtexparser.load(bibtex_file)
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\__init__.py", line 69, in load
    return parser.parse_file(bibtex_file)
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bparser.py", line 169, in parse_file
    return self.parse(file.read(), partial=partial)
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bparser.py", line 147, in parse
    self._expr.parseFile(bibtex_file_obj)
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bibtexexpression.py", line 278, in parseFile
    return self.main_expression.parseFile(file_obj, parseAll=True)
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 1907, in parse_file
    return self.parse_string(file_contents, parseAll)
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 1131, in parse_string
    loc, tokens = self._parse(instring, 0)
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 817, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 4891, in parseImpl
    return super().parseImpl(instring, loc, doActions)
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 4790, in parseImpl
    loc, tokens = self_expr_parse(instring, loc, doActions)
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 817, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 4114, in parseImpl
    return e._parse(
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 856, in _parseNoCache
    tokens = fn(instring, tokens_start, ret_tokens)
  File "D:\anzhuang2\anaconda3\lib\site-packages\pyparsing\core.py", line 291, in wrapper
    ret = func(*args[limit:])
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bparser.py", line 187, in <lambda>
    lambda s, l, t: self._add_entry(
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bparser.py", line 277, in _add_entry
    d[self._clean_field_key(key)] = self._clean_val(fields[key])
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bparser.py", line 228, in _clean_val
    return as_text(val)
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bibdatabase.py", line 270, in as_text
    return text_string_or_expression.get_value()
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bibdatabase.py", line 231, in get_value
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bibdatabase.py", line 231, in <listcomp>
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bibdatabase.py", line 197, in expand_string
    return string_or_bibdatastring.get_value()
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bibdatabase.py", line 178, in get_value
    return self._bibdatabase.expand_string(self.name)
  File "D:\anzhuang2\anaconda3\lib\site-packages\bibtexparser\bibdatabase.py", line 109, in expand_string
    raise(UndefinedString(name))
bibtexparser.bibdatabase.UndefinedString: 'apr'

**Comment by sheldonxxd** [comment]
你需要在 AuthorRanking 页面执行此 test。

**Comment by j89180192** [comment]
作者您好，我在authorranking页面执行了此test，结果如下
![image](https://user-images.githubusercontent.com/106729538/171652708-6e3b5dbd-a69f-4d04-ac7a-e8dc0863b841.png)
![image](https://user-images.githubusercontent.com/106729538/171652790-831934c9-cf2d-43d9-8065-fa1bc84b0711.png)
![image](https://user-images.githubusercontent.com/106729538/171652836-e479a617-c5a6-453d-bfe3-760398c3c3cf.png)

**Comment by j89180192** [comment]
![image](https://user-images.githubusercontent.com/106729538/171658364-ee0cbe19-ca90-46c1-a15a-9067c0dff65b.png)
这是我导入的mdnotes的格式，我确认了说明书上的每个步骤跟作者您保持一致的，应该不会是名字格式的问题导致的我想。

**Comment by sheldonxxd** [comment]
参考 #24

**Comment by j89180192** [comment]
![image](https://user-images.githubusercontent.com/106729538/171762789-784adc9b-6991-4cc8-b208-c1b9adadf5ef.png)
z作者您好，我学习到应该是better bibtex出现了问题，我的这里出现了“apr”，请问我这里应该输入什么呢/(ㄒoㄒ)/~~
我在网上搜索到 apr（在其他程序中报错时候）对应的是路径的问题？还是云里雾里的感觉😢
下面是我的配置全览，请看~
![image](https://user-images.githubusercontent.com/106729538/171764428-db777e50-b0b7-4030-b05f-d8389e187c87.png)
![image](https://user-images.githubusercontent.com/106729538/171764455-416b8fc6-cb26-482d-93c5-2c6e8d5b620a.png)
![image](https://user-images.githubusercontent.com/106729538/171764478-b1368067-374a-412d-89f8-42c2c6bf6f47.png)
![image](https://user-images.githubusercontent.com/106729538/171764512-7e160651-2a49-49dc-b124-fb698d350d82.png)
![image](https://user-images.githubusercontent.com/106729538/171764540-55002e29-0684-4387-8f51-47af57a63435.png)
![image](https://user-images.githubusercontent.com/106729538/171764566-b5bda2a7-ff8e-4113-bf94-92787cf7cd81.png)
![image](https://user-images.githubusercontent.com/106729538/171764589-b382658f-f851-42a1-bbd1-3f9b8e311a87.png)
![image](https://user-images.githubusercontent.com/106729538/171764631-96bb31b7-3f5a-489c-ad4d-3638b9e14c06.png)
![image](https://user-images.githubusercontent.com/106729538/171764671-8389c887-77b1-4648-b9f8-6ac3bd202dbe.png)
![image](https://user-images.githubusercontent.com/106729538/171764706-598e1fc1-dd39-45bd-8551-25776fbc04c8.png)

**Comment by sheldonxxd** [comment]
@j89180192 这应该是 zotero 中某些条目的异常造成的。omit 掉 apr 这个字段应该就可以了，但不排除还有其它奇怪的条目造成错误。本人常看文献多属于理工科的 journal article，如果是中文文献或者其它类型的 entry，都未经测试可能出错。

**Comment by j89180192** [comment]
作者您好，这是我的处理路线，但是结果还是弹出一模一样的错误，and我也看的是理工科的journal article/(ㄒoㄒ)/~~。
1.omit掉了apr
![image](https://user-images.githubusercontent.com/106729538/171877886-4fe62186-85f4-40f3-af47-eca086d3c9e3.png)
2.将zotero中的两篇文献分别创建mdnotes于obsidian的mdnotes文件夹中
![image](https://user-images.githubusercontent.com/106729538/171878588-0cd5408e-be4b-4e6e-a6f2-fd0e62752c26.png)
![image](https://user-images.githubusercontent.com/106729538/171878881-e720bdd3-7a0d-44cd-8d7c-c9ed5dae094d.png)
3.尝试点击作者统计按钮，显示失败。
![image](https://user-images.githubusercontent.com/106729538/171878975-883235be-cd4e-4952-beb8-0dd910579716.png)
4.在authorranking运行test，还是同上次显示的一样呜呜~
![image](https://user-images.githubusercontent.com/106729538/171879186-d821445d-5dec-43c1-b366-37aac3282a3a.png)
![image](https://user-images.githubusercontent.com/106729538/171879221-1657a259-daae-4afa-93a4-fdbd24506d29.png)

**Comment by j89180192** [comment]
我找到原因了，是因为我导出的文献库格式错误的设置为
![image](https://user-images.githubusercontent.com/106729538/171880832-7ceba026-1856-4cee-9924-21b570195328.png)
，而改正成输出库为  bettter biblatex格式后，再进行创建mdnotes问题就解决了。归根到底还是我有一部没能按照作者您的教程来，十分抱歉！因为我的失误耽误了作者大量的时间！
