### ISSUE TITLE
引文列表无效

### ISSUE THREAD

**Issue by YangXixi98** [sheldonxxd/obsidian_vault_template_for_researcher#44]
## ISSUE TEMPLATE

In order to solve the problem more efficiently, please submit the issue according to this template. 

### Environment

1. **Vault template release version**: v1.8
2. **Operating system**: windows
3. **Python version**: 3.9.12 (anaconda)
4. **Zotero version**: 6.0
5. **Pandoc version**: 2.18
6. **Obsidian version**: 0.14.15

### Bug descryption

在mdnotes的样例“@Doose2005”里“引文列表”正常使用，但存在部分文献“This reference does not have DOI 😵”
在自己的“@Wang2022”里“引文列表”无反应，/test后报错如下：

Traceback (most recent call last):
  File "C:\YangXixi\Research\08-Assets\Scripts\ref_list.py", line 78, in <module>
    main()
  File "C:\YangXixi\Research\08-Assets\Scripts\ref_list.py", line 19, in main
    entry = hwj.library[ckey]
KeyError: 'Wang2022'

### Obsidian console information

Uncaught TypeError: Cannot read properties of null (reading 'file')
    at eval (plugin:obsidian-float-toc-plugin:6451:26)
    at e.t.tryTrigger (app.js:1:910451)
    at e.t.trigger (app.js:1:910384)
    at e.trigger (app.js:1:1139440)
    at e.<anonymous> (app.js:1:1133611)
    at app.js:1:235084
    at Object.next (app.js:1:235189)
    at s (app.js:1:233928)

**Comment by YangXixi98** [comment]
找到问题了，是因为我自己忽略了“zotero-obsidian联动配置”中“导出「我的文库」到 Vault”这个步骤
