### ISSUE TITLE
插入引文列表无反应，QuickAdd: (LOG) TemplaterError: Error with User Template ref_list

### ISSUE THREAD

**Issue by MicYYX** [sheldonxxd/obsidian_vault_template_for_researcher#67]
### Environment

1. **Vault template release version**: v1.8
2. **Operating system**: windows 11
3. **Python version**: 3.9.7 (anaconda)
4. **Zotero version**: 6.0.20
5. **Pandoc version**: 2.12
6. **Obsidian version**: 1.1.9

### Bug descryption

使用QuickAdd中的“引文列表”功能后无反应

### Obsidian console information

QuickAdd: (LOG) TemplaterError: Error with User Template ref_list     plugin:quickadd:14760

运行
C:\Users\MichaelYin>python -u "X:\MicYin\08-Assets\Scripts\ref_list.py"
Traceback (most recent call last):
  File "X:\MicYin\08-Assets\Scripts\ref_list.py", line 78, in <module>
    main()
  File "X:\MicYin\08-Assets\Scripts\ref_list.py", line 9, in main
    fp = vault.inputs[1]
IndexError: list index out of range

感谢作者的模板库给我许多帮助。但奈何本人实在不懂变成，希望作者及各位大佬帮助。

**Comment by doc-zhong** [comment]
同问

**Comment by Tsuki-Gor** [comment]
你解决了么？我也遇到了这个问题，看起来好像是py文件中的问题，列表索引越界了？
